### ISSUE TITLE
compile_command.json contain invalid escape sequences

### ISSUE THREAD

**Issue by nordlow** [atilaneves/reggae#303] opened 2024-05-24 08:28 UTC
The "compile_commands.json" file produced by reggae contains invalid escape sequences making it impossible to parse it by standard-compliant JSON-parsers such as, for instance, `json-parse-string` in Emacs erroring as

```Debugger entered--Lisp error: (json-escape-sequence-error 2749 182 1806753)```

. This errors for the backslash in

```    {
        "directory": "/home/per/Work/SIL",
        "command": "bash -euxo pipefail -c 'export LD_LIBRARY_PATH=\"/home/per/dlang/dmd-2.108.0-sym4/linux/lib64:$${LD_LIBRARY_PATH:-}\"; cd plugins/extract; export LSAN_OPTIONS='\''suppressions=lsan.supp'\''; ../../tools/run_with_backtrace.sh bin/ut --esccodes'",
        "file": "plugins/extract/bin/ut"
    },```

. I would very much appreciate having this fixed because then I can adjust the Emacs D flychecker to use "compile_commands.json" which is massively gonna speed up my productivity developing D code in large projects. Now I manually have to copy the compile command.

I managed to make JSON parse by doing:

- Replacing all the `\''` with `\\''`.
- Replacing `\033` with `\\033`
- Replacing `\$` with `\\$`.

It might be as simple as adding an extra escaping slash in the string literals when the JSON is contructed by reggae.

**Comment by atilaneves** [comment] 2024-05-28 20:49
Duplicate of #291

**Closed by atilaneves** 2024-05-28 20:49 UTC
Labels: duplicate
