### ISSUE TITLE
Cannot bootstrap with latest version

### ISSUE THREAD

**Issue by moon-chilled** [atilaneves/reggae#60] opened 2019-09-11 03:44 UTC
Running `./bootstrap.sh ninja` fails with the following message:

```
Could not compile with args:
dmd -version=Have_reggae -m64 -g -debug -w -cov -unittest -I/home/elronnd/code/reggae -I/home/elronnd/code/reggae/payload -I/home/elronnd/code/reggae/src -J/home/elronnd/code/reggae/payload/reggae /home/elronnd/code/reggae/payload/reggae/backend/binary.d /home/elronnd/code/reggae/payload/reggae/backend/make.d /home/elronnd/code/reggae/payload/reggae/backend/ninja.d /home/elronnd/code/reggae/payload/reggae/backend/package.d /home/elronnd/code/reggae/payload/reggae/backend/tup.d /home/elronnd/code/reggae/payload/reggae/build.d /home/elronnd/code/reggae/payload/reggae/buildgen.d /home/elronnd/code/reggae/payload/reggae/config.d /home/elronnd/code/reggae/payload/reggae/core/package.d /home/elronnd/code/reggae/payload/reggae/core/rules/package.d /home/elronnd/code/reggae/payload/reggae/ctaa.d /home/elronnd/code/reggae/payload/reggae/dependencies.d /home/elronnd/code/reggae/payload/reggae/dub/info.d /home/elronnd/code/reggae/payload/reggae/file.d /home/elronnd/code/reggae/payload/reggae/options.d /home/elronnd/code/reggae/payload/reggae/package.d /home/elronnd/code/reggae/payload/reggae/path.d /home/elronnd/code/reggae/payload/reggae/range.d /home/elronnd/code/reggae/payload/reggae/reflect.d /home/elronnd/code/reggae/payload/reggae/rules/c_and_cpp.d /home/elronnd/code/reggae/payload/reggae/rules/common.d /home/elronnd/code/reggae/payload/reggae/rules/d.d /home/elronnd/code/reggae/payload/reggae/rules/dub.d /home/elronnd/code/reggae/payload/reggae/rules/package.d /home/elronnd/code/reggae/payload/reggae/sorting.d /home/elronnd/code/reggae/payload/reggae/types.d /home/elronnd/code/reggae/src/reggae/dub/interop.d /home/elronnd/code/reggae/src/reggae/dub/json.d /home/elronnd/code/reggae/src/reggae/from.d /home/elronnd/code/reggae/src/reggae/io.d /home/elronnd/code/reggae/src/reggae/json_build.d /home/elronnd/code/reggae/src/reggae/reggae.d /home/elronnd/code/reggae/src/reggae/reggae_main.d -of.reggae/objs/ut.objs/home/elronnd/code/reggae/payload/reggae/backend.o -c
/home/elronnd/code/reggae/tests/utils.d(4): Error: module `unit_threaded` is in file 'unit_threaded.d' which cannot be read
import path[0] = /home/elronnd/code/reggae
import path[1] = /home/elronnd/code/reggae/payload
import path[2] = /home/elronnd/code/reggae/src
import path[3] = /usr/include/dlang/dmd
```

**Comment by atilaneves** [comment] 2020-04-21 11:29
This must have been fixed in the meanwhile, since I can't reproduce it.

**Closed by atilaneves** 2020-04-21 11:29 UTC
